openapi: 3.0.3
info:
  title: ""
  version: 0.0.0
paths:
  /api/ai/exercise/:
    get:
      operationId: api_ai_exercise_retrieve
      tags:
        - api
      security:
        - {}
      responses:
        "200":
          description: No response body
  /api/gemini/gen_fill_blank/:
    get:
      operationId: api_gemini_gen_fill_blank_retrieve
      tags:
        - api
      security:
        - {}
      responses:
        "200":
          description: No response body
    post:
      operationId: api_gemini_gen_fill_blank_create
      tags:
        - api
      security:
        - {}
      responses:
        "200":
          description: No response body
  /api/login/:
    post:
      operationId: api_login_create
      tags:
        - api
      security:
        - jwtAuth: []
        - {}
      responses:
        "200":
          description: No response body
  /api/note/all/:
    get:
      operationId: api_note_all_retrieve
      tags:
        - api
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
          description: ""
  /api/note/paginated/:
    get:
      operationId: api_note_paginated_list
      parameters:
        - name: page
          required: false
          in: query
          description: A page number within the paginated result set.
          schema:
            type: integer
        - name: page_size
          required: false
          in: query
          description: Number of results to return per page.
          schema:
            type: integer
      tags:
        - api
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedTopicList"
          description: ""
  /api/token/:
    post:
      operationId: api_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenObtainPair"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/TokenObtainPair"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/TokenObtainPair"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenObtainPair"
          description: ""
  /api/token/refresh/:
    post:
      operationId: api_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenRefresh"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/TokenRefresh"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/TokenRefresh"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenRefresh"
          description: ""
  /api/topic/{id}/:
    get:
      operationId: api_topic_retrieve
      description: |-
        GET    /topics/<pk>/   -> retrieve
        DELETE /topics/<pk>/   -> delete
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      tags:
        - api
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Topic"
          description: ""
    put:
      operationId: api_topic_update
      description: |-
        GET    /topics/<pk>/   -> retrieve
        DELETE /topics/<pk>/   -> delete
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Topic"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Topic"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/Topic"
        required: true
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Topic"
          description: ""
    patch:
      operationId: api_topic_partial_update
      description: |-
        GET    /topics/<pk>/   -> retrieve
        DELETE /topics/<pk>/   -> delete
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchedTopic"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/PatchedTopic"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/PatchedTopic"
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Topic"
          description: ""
    delete:
      operationId: api_topic_destroy
      description: |-
        GET    /topics/<pk>/   -> retrieve
        DELETE /topics/<pk>/   -> delete
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      tags:
        - api
      security:
        - jwtAuth: []
      responses:
        "204":
          description: No response body
  /api/topic/{id}/add-word/{query}/:
    post:
      operationId: api_topic_add_word_create
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
        - in: path
          name: query
          schema:
            type: string
          required: true
      tags:
        - api
      security:
        - jwtAuth: []
      responses:
        "200":
          description: No response body
  /api/topic/{id}/delete-word/{voca_topic_id}/{voca_detail_id}/:
    get:
      operationId: api_topic_delete_word_retrieve
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
        - in: path
          name: voca_detail_id
          schema:
            type: integer
          required: true
        - in: path
          name: voca_topic_id
          schema:
            type: integer
          required: true
      tags:
        - api
      security:
        - jwtAuth: []
      responses:
        "200":
          description: No response body
    delete:
      operationId: api_topic_delete_word_destroy
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
        - in: path
          name: voca_detail_id
          schema:
            type: integer
          required: true
        - in: path
          name: voca_topic_id
          schema:
            type: integer
          required: true
      tags:
        - api
      security:
        - jwtAuth: []
      responses:
        "204":
          description: No response body
  /api/topics/:
    get:
      operationId: api_topics_list
      tags:
        - api
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Topic"
          description: ""
    post:
      operationId: api_topics_create
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Topic"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Topic"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/Topic"
        required: true
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Topic"
          description: ""
  /api/topics/search/:
    get:
      operationId: api_topics_search_list
      tags:
        - api
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Topic"
          description: ""
  /api/user/me/:
    get:
      operationId: api_user_me_retrieve
      tags:
        - api
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          description: ""
    put:
      operationId: api_user_me_update
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/User"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          description: ""
    patch:
      operationId: api_user_me_partial_update
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchedUser"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/PatchedUser"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/PatchedUser"
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          description: ""
    delete:
      operationId: api_user_me_destroy
      tags:
        - api
      security:
        - jwtAuth: []
      responses:
        "204":
          description: No response body
  /api/users/:
    get:
      operationId: api_users_list
      tags:
        - api
      security:
        - jwtAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
          description: ""
    post:
      operationId: api_users_create
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/User"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      security:
        - {}
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          description: ""
components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        topics_data:
          type: string
          readOnly: true
      required:
        - created_at
        - id
        - topics_data
        - updated_at
    PaginatedTopicList:
      type: object
      required:
        - count
        - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: "#/components/schemas/Topic"
    PatchedTopic:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 200
        words:
          type: string
          writeOnly: true
        vocas:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
    PatchedUser:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          maxLength: 150
        email:
          type: string
          format: email
        fullname:
          type: string
          maxLength: 255
        password:
          type: string
          writeOnly: true
          minLength: 6
        firebase_id:
          type: string
          maxLength: 255
        created_at:
          type: string
          format: date-time
          readOnly: true
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
        - access
        - password
        - refresh
        - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
        - access
        - refresh
    Topic:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 200
        words:
          type: string
          writeOnly: true
        vocas:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
        - created_at
        - id
        - title
        - updated_at
        - vocas
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          maxLength: 150
        email:
          type: string
          format: email
        fullname:
          type: string
          maxLength: 255
        password:
          type: string
          writeOnly: true
          minLength: 6
        firebase_id:
          type: string
          maxLength: 255
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
        - created_at
        - firebase_id
        - fullname
        - id
        - password
        - username
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
